apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-test
spec:
  selector:
    matchLabels:
      app: k8s-test
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-test
    spec:
      containers:
      - name: k8s-test
        image: k8s-test
        ports:
        - containerPort: 80